#!/usr/bin/env python3

import sys
from src import runFile, runPrompt

if __name__ == '__main__':
    if len(sys.argv) > 2:
        print("Usage: tarnish [script]")
        exit(64)
    elif len(sys.argv) == 2:
        runFile(sys.argv[1])
    else:
        runPrompt()
